name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8 AM; adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run the LeetCode Sync action
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          filter-duplicate-secs: 0       # Sync every accepted submission
          verbose: true                  # Provides extra details in the commit message
          commit-header: "[Sync]:"  # Customized commit header

      # Step 3: Rename solution files to include a timestamp for uniqueness
      - name: Rename Files with Readable Timestamp
        run: |
          # Loop through each problem directory
          for dir in */; do
            # Loop through files that start with "solution." regardless of extension
            for file in "$dir"solution.*; do
              # If no matching file exists, continue to next iteration
              [ -f "$file" ] || continue
              # Extract the file extension using parameter expansion
              ext="${file##*.}"
              # Generate a readable timestamp, e.g., 2025-03-23_08-00-00
              timestamp=$(date "+%Y-%m-%d_%H-%M-%S")
              # Rename the file to include the timestamp
              mv "$file" "${dir}solution_${timestamp}.${ext}"
            done
          done

