name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8 AM; adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run the LeetCode Sync action
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          filter-duplicate-secs: 0       # Sync every accepted submission
          verbose: true                  # Provides extra details in the commit message
          commit-header: "[Sync]:"  # Customized commit header

      # Step 3: Rename solution files to include a timestamp for uniqueness
      - name: Rename Files for Uniqueness
        run: |
          # List of file extensions to process (add or remove as needed)
          for ext in cpp py js java ts rb go cs swift kt; do
            # Loop through files matching the extension in the current directory
            for file in *.$ext; do
              # If no file found matching the pattern, skip to next iteration
              [ -e "$file" ] || continue
              # Check if the file does not already include an underscore (indicating a timestamp)
              if [[ "$file" != *_* ]]; then
                base=$(basename "$file" ."$ext")
                # Rename the file by appending the current Unix timestamp
                mv "$file" "${base}_$(date +%s).$ext"
              fi
            done
          done
